android { namespace = 'com.squareup.ui.compose.overlays' }

dependencies {
  api 'androidx.compose.runtime:runtime:1.12.1'
  api 'androidx.compose.runtime:runtime-saveable:1.12.1'
  api 'androidx.compose.ui:ui:1.12.1'
  api 'androidx.compose.foundation:foundation:1.12.1'
  api 'androidx.compose.animation:animation-core:1.12.1'
  api 'androidx.lifecycle:lifecycle-runtime:2.9.4'
  implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.9.4'
  implementation 'androidx.compose.foundation:foundation-layout:1.12.1'
  implementation 'androidx.compose.ui:ui-util:1.12.1'
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'com.google.truth:truth:1.4.5'
  androidTestImplementation 'androidx.core:core:1.13.1'
  androidTestImplementation 'androidx.compose.ui:ui-test-junit4:1.12.1'
  androidTestImplementation 'androidx.compose.ui:ui-test-manifest:1.12.1'
  androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
  androidTestImplementation 'androidx.test:rules:1.6.1'
  androidTestImplementation 'com.google.truth:truth:1.4.5'
  androidTestImplementation 'androidx.lifecycle:lifecycle-runtime-testing:2.9.2'
}
